package rules;

import com.example.demo.runtime.rule.RuleContext;

import com.example.demo.model.*;
import com.example.demo.service.*;

global ValidationReport validationReport;
global ReportFactory reportFactory;
global BankingInquiryService inquiryService;

import function com.example.demo.service.ValidationHelper.error;
import function com.example.demo.service.ValidationHelper.warning;

    rule "addressRequired"
       when
          Customer( address == null )
       then
          warning(kcontext);
    end
    rule "phoneNumberRequired"
       when
          Customer( phoneNumber == null || == "" )
       then
          error(kcontext);
    end
    rule "accountOwnerRequired"
      when
         $account : Account( owner == null )
      then
         error(kcontext, $account);
    end